name: AQI Logger

on:
  schedule:
    - cron: "0 * * * *"   # каждый час
  workflow_dispatch: {}    # можно запускать руками

jobs:
  run-aqi-logger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AQI logger
        env:
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          python aqi_logger.py
